version: '3.9'
services:
  jdk:
    build:
      context: .
      dockerfile: 'JdkDockerfile'
    container_name: 'jdk'
    init: true
    volumes:
      - './mounted-jdk:/home/work'
    ports:
      - '8080:8080'
  node:
    build:
      context: .
      dockerfile: 'NodeDockerfile'
    container_name: 'node'
    init: true
    volumes:
      - './mounted-node:/home/node'
    ports:
      - '5173:5173'