/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.59).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.demo.api.controller;

import com.example.demo.api.model.RequestPiyo;
import com.example.demo.api.model.ResponsePiyo;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-07-27T00:47:25.420785308Z[Etc/UTC]")
@Validated
public interface PiyoApi {

    @Operation(summary = "これはpiyoの概要", description = "これはpiyoの説明", tags={ "piyo" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "これはpiyoのレスポンスの説明", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponsePiyo.class))) })
    @RequestMapping(value = "/piyo",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponsePiyo> piyoPost(@Parameter(in = ParameterIn.DEFAULT, description = "これはpiyoのリクエストボディの説明", required=true, schema=@Schema()) @Valid @RequestBody RequestPiyo body
);

}

