openapi: 3.0.3
info:
  title: vue-rest-trial
  description: |-
    これはRESTAPIリファレンス
  version: 1.0.11
externalDocs:
  description: GitHub
  url: https://github.com/sh1Nome/vue-rest-trial
tags:
  - name: hoge
    description: hogehoge
  - name: fuga
    description: fugafuga
  - name: piyo
    description: piyopiyo
paths:
  /hoge:
    get:
      tags:
       - hoge
      summary: これはhogeの概要
      description: |-
        これはhogeの説明
      responses:
        200:
          description: |-
            これはhogeのレスポンスの説明
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseHogeFuga'
  /fuga:
    get:
      tags:
       - fuga
      summary: これはfugaの概要
      description: |-
        これはfugaの説明
      responses:
        200:
          description: |-
            これはfugaのレスポンスの説明
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseHogeFuga'
  /piyo:
    post:
      tags:
       - piyo
      summary: これはpiyoの概要
      description: |-
        これはpiyoの説明
      requestBody:
        description: |-
          これはpiyoのリクエストボディの説明
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestPiyo'
        required: true
      responses:
        200:
          description: |-
            これはpiyoのレスポンスの説明
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsePiyo'
components:
  schemas:
    RequestPiyo:
      type: object
      required:
        - greeting
      properties:
        greeting:
          type: string
          description: あいさつ
    ResponseHogeFuga:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 画面名
    ResponsePiyo:
      type: object
      required:
        - name
        - greeting
      properties:
        name:
          type: string
          description: 画面名
        greeting:
          type: string
          description: あいさつ